<<<<<<< HEAD
name: version_promotion_dev_staging

on:
  push:
    branches: [ "master" ]
    paths:
      - 'envs/dev/version.yml'

jobs:

  promote-version:
    runs-on: ubuntu-latest
    name: Promote version from dev to staging

    steps:
    
        - name: Checkout gitops-environment-promotion-01
          uses: actions/checkout@v3
          with:
            repository: JavadZahrabi/gitops-environment-promotion-01
            path: ./gitops-environment-promotion-01

        - name: copy file
          run: |
              cp -R ./gitops-environment-promotion-01/envs/dev/version.yml ./gitops-environment-promotion-01/envs/staging


        - name: Push version to staging
          run: |
            cd ./gitops-environment-promotion-01
            git add .
            git config user.name JavadZahrabi
            git config user.email ja.zahrabi@gmail.com
            git commit -am "version.yml promoted to staging"
            git push
=======
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
>>>>>>> 27cb4ce2f3e16a5fa212e59a7d448f900d52e634
